// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solucion;

#nullable disable

namespace Solucion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231010192734_migra4")]
    partial class migra4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solucion.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Solucion.CuentaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClienteId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdClienteId");

                    b.ToTable("CuentaBancarias");
                });

            modelBuilder.Entity("Solucion.TarjetaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuentaBancariaId")
                        .HasColumnType("int");

                    b.Property<double>("LimiteCredito")
                        .HasColumnType("float");

                    b.Property<double>("MontoDeuda")
                        .HasColumnType("float");

                    b.Property<int>("NumeroTarjeta")
                        .HasColumnType("int");

                    b.Property<double>("SaldoDisponible")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCuentaBancariaId");

                    b.ToTable("TarjetaCreditos");
                });

            modelBuilder.Entity("Solucion.CuentaBancaria", b =>
                {
                    b.HasOne("Solucion.Cliente", "IdCliente")
                        .WithMany()
                        .HasForeignKey("IdClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCliente");
                });

            modelBuilder.Entity("Solucion.TarjetaCredito", b =>
                {
                    b.HasOne("Solucion.CuentaBancaria", "IdCuentaBancaria")
                        .WithMany()
                        .HasForeignKey("IdCuentaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCuentaBancaria");
                });
#pragma warning restore 612, 618
        }
    }
}
